[Rainmeter]
Update=3000
DefaultUpdateDivider=-1
OnUpdateAction=[!UpdateMeter ShapeStroke][!Redraw]
OnFocusAction=[!SetOption ShapeStroke FillColor "Fill Color [*Accent*]"][!UpdateMeter ShapeStroke][!Redraw]
;[!SetVariable Contrast Focus][!HideMeter CloseUnfocus][!ShowMeter CloseFocus][!ShowMeter MinimizeFocus][!HideMeter MinimizeUnfocus]
OnUnfocusAction=[!SetOption ShapeStroke FillColor "Fill Color 255,255,255,32"][!UpdateMeter ShapeStroke][!Redraw]
;[!SetVariable Contrast Unfocus][!HideMeter CloseFocus][!ShowMeter CloseUnfocus][!HideMeter MinimizeFocus][!ShowMeter MinimizeUnfocus]

;    - - - - - - - - -
;   - - -Variables- - -
;    - - - - - - - - -

[Variables]
BodyWidth=300
BodyHeight=300

Contrast=Unfocus
ContrastFocus=#Lumens#
ContrastUnfocus=255,255,255

;    - - - - - - - - -
;   - - -Measures - - -
;    - - - - - - - - -

; Windows Accent Color
[Accent]
Measure=Plugin
Plugin=SysColor
UpdateDivider=1

; Contrast
[LumensScript]
Measure=Script
ScriptFile="#CURRENTPATH#ColorPicker\Extra\Scripts\HSBLib.lua"
[LumensMeasure]
Measure=Calc
UpdateDivider=1
IfCondition=[&LumensScript:ColorLumens("[&Accent]")] > 50
IfTrueAction=[!SetVariable Lumens 0,0,0][!UpdateMeterGroup Contrast][!Redraw]
IfFalseAction=[!SetVariable Lumens 255,255,255][!UpdateMeterGroup Contrast][!Redraw]
DynamicVariables=1

;    - - - - - - - -
;   - - -Styles - - -
;    - - - - - - - -

[TextStyle]
FontFace=Segoe UI
FontColor=255,255,255
AntiAlias=1

[GroundBarTextStyle]
Y=(#BodyHeight#-21)
FontSize=8.6
FontFace=Segoe UI
FontColor=204,204,204
FontWeight=640
AntiAlias=1

[ContentTextStyle]
FontSize=11
FontFace=Consolas
FontColor=255,255,255
AntiAlias=1

;    - - - - - - -
;   - - -Body- - -
;    - - - - - - -

[ShapeStroke]
Meter=Shape
Shape=Rectangle 0,0,(#BodyWidth#+2),(#BodyHeight#+2),4 | StrokeWidth 0 | Extend FillColor
FillColor=Fill Color 255,255,255,32
DynamicVariables=1

[Shape]
Meter=Shape
;Background
Shape=Rectangle 1,1,#BodyWidth#,#BodyHeight# | StrokeWidth 0 | Fill Color 39,39,39
Container=Container
; Save
;Shape=Line 1,71.5,(#BodyWidth#+1),71.5 | StrokeWidth 1 | Stroke Color 29,29,29
[Container]
Meter=Shape
Shape=Rectangle 1,1,#BodyWidth#,#BodyHeight#,4

;    - - - - - - - -
;   - - -TopBar - - -
;    - - - - - - - -

[TopBarTitle]
Meter=String
;Text=Color Picker
X=47
Y=7
FontSize=8.7
MeterStyle=TextStyle

[TopBarIcon]
Meter=Image
;ImageName="#CURRENTPATH#Extra\Images\icon.png"
X=17
Y=8
W=16
H=16

;   - - -Close - - -
[CloseUnfocus]
Meter=Shape
;Shape=Line (#BodyWidth#-27),10,(#BodyWidth#-17),20 | StrokeWidth 1 | Stroke Color 255,255,255,128
;Shape2=Line (#BodyWidth#-27),20,(#BodyWidth#-17),10 | StrokeWidth 1 | Stroke Color 255,255,255,128
[CloseFocus]
Meter=Shape
;Shape=Line (#BodyWidth#-27),10,(#BodyWidth#-17),20 | StrokeWidth 1 | Stroke Color #Lumens#
;Shape2=Line (#BodyWidth#-27),20,(#BodyWidth#-17),10 | StrokeWidth 1 | Stroke Color #Lumens#
DynamicVariables=1
Hidden=1
[CloseHover]
Meter=Shape
;Shape=Rectangle (#BodyWidth#-44),1,45,29 | StrokeWidth 0 | Extend FillColor
;Shape2=Line (#BodyWidth#-27),10,(#BodyWidth#-17),20 | StrokeWidth 1 | Extend Cross
;Shape3=Line (#BodyWidth#-27),20,(#BodyWidth#-17),10 | StrokeWidth 1 | Extend Cross
FillColor=Fill Color 0,0,0,0
Cross=Stroke Color 0,0,0,0
MouseOverAction=[!SetOption #CURRENTSECTION# FillColor "Fill Color 196,43,28"][!SetOption #CURRENTSECTION# Cross "Stroke Color 255,255,255"][!UpdateMeter #CURRENTSECTION#][!Redraw]
MouseLeaveAction=[!SetOption #CURRENTSECTION# FillColor "Fill Color 0,0,0,0"][!SetOption #CURRENTSECTION# Cross "Stroke Color 0,0,0,0"][!UpdateMeter #CURRENTSECTION#][!Redraw]
LeftMouseUpAction=[!DeactivateConfig][!WriteKeyValue Variables Section Main]
Container=Container

;   - - -Minimize- - -
[MinimizeUnfocus]
Meter=Shape
;Shape=Line (#BodyWidth#-71),15.5,(#BodyWidth#-61),15.5 | StrokeWidth 1 | Stroke Color 255,255,255,128
[MinimizeFocus]
Meter=Shape
;Shape=Line (#BodyWidth#-71),15.5,(#BodyWidth#-61),15.5 | StrokeWidth 1 | Stroke Color #Lumens#
DynamicVariables=1
Hidden=1
[MinimizeHover]
Meter=Shape
;Shape=Rectangle (#BodyWidth#-90),1,45,29 | StrokeWidth 0 | Extend Hover
;Shape2=Line (#BodyWidth#-71),15.5,(#BodyWidth#-61),15.5 | StrokeWidth 1 | Extend Line
Hover=Fill Color 0,0,0,0
Line=Stroke Color 0,0,0,0
MouseOverAction=[!SetOption #CURRENTSECTION# Hover "Fill Color [#Contrast[#Contrast]],16"][!SetOption #CURRENTSECTION# Line "Stroke Color [#Contrast[#Contrast]]"][!UpdateMeter #CURRENTSECTION#][!Redraw]
MouseLeaveAction=[!SetOption #CURRENTSECTION# Hover "Fill Color 0,0,0,0"][!SetOption #CURRENTSECTION# Line "Stroke Color 0,0,0,0"][!UpdateMeter #CURRENTSECTION#][!Redraw]
LeftMouseUpAction=[!ActivateConfig "#CURRENTCONFIG#\Minimized"][!ShowFade "#CURRENTCONFIG#\Minimized"][!DeactivateConfig][!HideFade]
