[Variables]
@IncludeVariables="#@#ProfileVariables.inc"

; Wallpaper Engine Executable Path
WEPath=C:\Program Files (x86)\Steam\steamapps\common\wallpaper_engine\wallpaper32.exe

; Skin Offset
OffsetX=0
OffsetY=0

;    - - - - - - - - - - - - - - - - - -
;   - - -set your profile names here- - -
;    - - - - - - - - - - - - - - - - - -

; Wallpaper Engine Profiles - (Default: "profileNUMBER")
;Profile1=Theme1
;Profile2=Theme2
;...

; Rainmeter Layouts - (Default: "profileNUMBER")
;Layout1=Theme1
;Layout2=Theme2
;...

;    - - - - - - -
;   - - -Main - - -
;    - - - - - - -

; Profile Count
Profiles_Count=3
; Rows and Columns
Profiles_GridColumns=3
Profiles_GridRows=1

; Profile Alignment - (Options: Horizontal: H, Vertical: V)
Profiles_Alignment=V

;    - - - - - - -
;   - - -Shape- - -
;    - - - - - - -

; Profiles Icon Size
Profiles_IconSize=128

; Profiles Frame Width
Profiles_StrokeWidth=4

; Background Frame Width
Background_StrokeWidth=4

; Profiles Gap
Profiles_Gap=16

; Background Frame Padding
Background_PaddingTop=16
Background_PaddingBottom=16
Background_PaddingRight=16
Background_PaddingLeft=16

; Profile Corners
Profiles_Corners=8

; Background Corners
Background_Corners=16

;    - - - - - - - -
;   - - -Colors - - -
;    - - - - - - - -

; Background Fill Color
Background_FillColor=32,32,32
Background_FillOpacity=64

; Profiles Frame Color
Profiles_StrokeColor=0,0,0
Profiles_StrokeOpacity=255

; Background Frame Color
Background_StrokeColor=0,0,0
Background_StrokeOpacity=255

; Profiles OnHover Effect
Profiles_OnHoverColor=192,192,192
Profiles_OnHoverOpacity=32
